### ISSUE TITLE
v1.1-preview1 breaks compatibility with .NET 5.0 SDKs older than 5.0.406

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#2334]
After upgrading to 1.1-preview1, compilation errors ensued:

```
Error This version of WindowsAppSDK requires WinRT.Runtime.dll version 1.5 or greater.
    Please update to .NET SDK 5.0.212 or 5.0.406 (or later).
    Or add a temporary Microsoft.Windows.SDK.NET.Ref reference of version 10.0.*.23 or later.
    For example,
        <PropertyGroup>
            <WindowsSdkPackageVersion>10.0.<Target Windows SDK Build Number>.23</WindowsSdkPackageVersion>
        </PropertyGroup>

Warning	MSB3277	Found conflicts between different versions of "WinRT.Runtime" that could not be resolved.
There was a conflict between "WinRT.Runtime, Version=1.4.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=1.5.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709".
...
```

I was not expecting any new dependencies or failures per [documented/agreed upon version number expectations](https://github.com/microsoft/WindowsAppSDK/discussions/637).

I did later discover the documentation has this blurb, confirming the new dependency:
> If you're using C# with 1.1.0 Preview 1, then you must use one of the following .NET SDK versions at a minimum: .NET SDK 6.0.201, 6.0.103, 5.0.212, or 5.0.406. To upgrade your .NET SDK, you can update to the latest version of Visual Studio, or visit Download .NET.
-- https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#other-limitations-and-known-issues

**Comment by MuyuanMS** [comment]
Close this issue on 1.1 as part of old issue cleanup.
