### PR TITLE
[1.8-stable] Add Microsoft.FrameworkUdk dependency to installer project

### PR DESCRIPTION
**Pull request by agniuks**
## Problem
 The CreateInstaller stage in the aggregator pipeline fails with:

InstallActivityContext.cpp(7,10): Error C1083: Cannot open include file: 'FrameworkUdk/Containment.h': No such file
or directory

 
 This blocks all official and PR builds on release/1.8-stable.
 
 ## Root Cause
 `InstallActivityContext.cpp` was updated to `#include <FrameworkUdk/Containment.h>`
 for A/B containment support (bug 61543987), but the installer project
 (`WindowsAppRuntimeInstall.vcxproj`) was never updated to import the
 `Microsoft.FrameworkUdk` NuGet targets. The FrameworkUdk package is already
 restored by the pipeline via `ConvertVersionDetailsToPackageConfig`, but without
 the `.targets` import the compiler can't find the headers.

 #6330
 
 ## Fix
 Add `Microsoft.FrameworkUdk.targets` import and existence check to
 `WindowsAppRuntimeInstall.vcxproj`, matching the pattern used by
 `WindowsAppRuntime_DLL.vcxproj` and other projects in the repo.

### CODE REVIEW

**Review by ssparach — APPROVED** [review]

**Comment by DrusTheAxe** [comment]
Won't this make WindowsAppRuntimeInstall.exe dependent on the FrUdk.dll? So now I can't distribute and run WindowsAppRuntimeInstall.exe as it'll fail to find/load that DLL

Kinda kills the ease of use.

Is FrUdk .dll downloadable from https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads? All those Installer links won't work unless you _also_ download the FrUdk dll (and the right version at that) and put it _next to_ the installer .exe.

And, inevitably, some folks will drop it into System32 which will cause more mayhem for developers, users, and us - "_sometimes_ the installer won't run", depending on the version laying around in the System32 mosh pit vs the version of installer .exe, plus it can potentially interfere with product execution in some odd cases. (It shouldn't, if everything is placed and hold exactly right, but that's impractical to expect 100%).

All around BadMojo(TM) :-(

**Comment by DrusTheAxe** [comment]
>InstallActivityContext.cpp(7,10): Error C1083: Cannot open include file

Why does it use this at all?

Who's going to set the context _inside the _Installer_ process to enable this?

You're essentially trying to use standard containment mechanisms meant for application runtime _inside the servicing stack_. This generally doesn't work because of the fundamental differences (Ask me how I know :P)

There are options but it gets complicated. Perhaps we should talk offline.

**Review by DrusTheAxe — CHANGES_REQUESTED** [review]
I see a fundamental problem here. See comments
